local STRINGS = GLOBAL.STRINGS
-- 
STRINGS.NAMES.FRUIT_SKEWERS = "果串零食"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT_SKEWERS = "ohhh~"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT_SKEWERS = "ohhh~"
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT_SKEWERS = "ohhh~"

-- 
STRINGS.NAMES.ICE_HONEY_BLACK_TEA = "冰蜜红茶"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ICE_HONEY_BLACK_TEA = "ohhh~"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ICE_HONEY_BLACK_TEA = "ohhh~"
STRINGS.CHARACTERS.WENDY.DESCRIBE.ICE_HONEY_BLACK_TEA = "ohhh~"

-- 
STRINGS.NAMES.WATERMELON_BO = "西瓜啵"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WATERMELON_BO = "ohhh~"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WATERMELON_BO = "ohhh~"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WATERMELON_BO = "ohhh~"